config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'docs/index'
  get 'docs/show'
  get 'docs/new'
  get 'docs/create'
  get 'docs/edit'
  get 'docs/update'
  get 'docs/destroy'
  get 'welcome/index'
  resources :docs

  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: %i[show update destroy edit]
  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= form_with scope: :doc, url: docs_path, local: true do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :content %>
    <%= form.text_area :content %>
    <%= form.submit class: "button"%>
<% end %>

app/views/docs/create.html.erb
<h1>Docs#create</h1>
<p>Find me in app/views/docs/create.html.erb</p>

app/views/docs/destroy.html.erb
<h1>Docs#destroy</h1>
<p>Find me in app/views/docs/destroy.html.erb</p>

app/views/docs/edit.html.erb
<div class="wrapper_with_padding">
  <h1> Edit Document </h1>
  <%= render 'form' %>
</div>

app/views/docs/index.html.erb
<div class="wrapper_with_padding">
  <div id="docs" class="clearfix">
    <% unless @docs.blank? %>
      <% @docs.each do |doc| %>
        <a href="<%= url_for(doc) %>">
          <div class="doc">
            <p class="title">
              <%= doc.title%>
            </p>
            <p class="date">
              <%= time_ago_in_words(doc.created_at) %>
            </p>
            <p class="content">
              <%= truncate(doc.content, length:50) %>
            </p>
          </div>
        </a>
      <% end %>
    <%else%>
      <h2>Create Doc!</h2>
      <p>Start Creating Documents and Organizing Your Life</p>
      <%= button_to "Create Docment" ,new_doc_path , :method => :get %>
    <% end %>
  </div>
</div>

app/views/docs/new.html.erb
<div class="wrapper_with_padding">
  <h1> New Document </h1>
  <%= render 'form' %>
</div>

app/views/docs/show.html.erb
<div class="wrapper_with_padding">
  <div id="doc_show">
    <h2 class="title">
      <%= @doc.title %>
    </h2>
    <p>
      <%= simple_format(@doc.content) %>
    </p>
    <div class="buttons">
      <%= link_to "Update" ,edit_doc_path(@doc), class: "button"%>
      <%= link_to "Delete" ,doc_path(@doc), :method => :delete, data: {confirm: "Are you sure ?"}, class: "button"%>
    </div>
  </div>
</div>

app/views/docs/update.html.erb
<h1>Docs#update</h1>
<p>Find me in app/views/docs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet | Your Life's work!</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <header>
      <div class=header_inner>
        <%= link_to "FileCabinet", root_path, id: "logo"%>
        <nav>
          <% if user_signed_in? %>
            <%= link_to "Create Doc", new_doc_path %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log In", new_user_session_path  %>
          <% end %>
        </nav>
      <div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
      <h1>File Cabinet</h1>
      <p> Your Life's work. Organized, always.</p>
      <button type="button" name="button"><%=link_to "Enter", new_user_registration_path%></button>
    </div>
</div>

<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">
      <div class="callout">
        <h2>Organize</h2>
        <p>Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test </p>
      </div>
    </div>
  </div>
</div>

<div id="bottom_cta">
  <div class="wrapper">
    <h2>Go Ahead!</h2>
    <br>
    <button type="button" name="button"><%=link_to "Join Now", new_user_registration_path%></button>
  </div>

</div>